version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - '6379:6379'

  rate-limiter:
    build: .
    container_name: rate-limiter
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: npm run start:prod
